### PR TITLE
Chore/filmo 005 setup pull request template

### PR DESCRIPTION
**Pull request by kntmicheal**
## Description
- adding pull_request_template 

## Type of change
Please select the relevant option

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Please describe the tests that you ran to verify your change
- [ ] End to end
- [ ] Integration
- [ ] Unit testing
- [ ] N/A

## How to Manually Test
- Checkout to this branch
- On the role management tab, click on `view all features`
- On the all features page, click on aff feature
- On the modal pop up, input the feature name and the permissions
- Enter to add each permission added
- Click submit to create

## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have linted my code prior to submission
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generates no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by WinnersProx** [comment]
Good job @kntmicheal ,

However, i'd suggest you to change the file name to ```PULL_REQUEST_TEMPLATE.md``` and your ```README.MD``` to ```README.md```

I think that spelling the extension in lowercase is the best practice

**Comment by aaronsekisambu** [comment]
@kntmicheal Good work.
1. Please make sure to edit how to test manually section and fit in how to test your branch rather leaving the default one

2. You have 6 commits squash them into a single commit please

**Comment by aaronsekisambu** [comment]
> Good job @kntmicheal ,
> 
> However, i'd suggest you to change the file name to `PULL_REQUEST_TEMPLATE.md` and your `README.MD` to `README.md`
> 
> I think that spelling the extension in lowercase is the best practice

@WinnersProx The file extension should be caps like ``.MD`` so no need to change it

**Comment by dnuwa** [comment]
@WinnersProx kindly work on the feedback so we can get this PR merged.
Squash these 10 commits into one.

**Pull request closed without merging**
