### PR TITLE
FILMO-003 Coveralls Coverage

### PR DESCRIPTION
**Pull request by BenjaminKyamanywa**
## Description
- Added coveralls coverage badge to ReadMe file to show how code coverage has changed with the new build, and what isn't covered by tests for the filmo project. 

## Type of change
Please select the relevant option

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?
Please describe the tests that you ran to verify your change
- [ ] End to end
- [ ] Integration
- [ ] Unit testing
- [x] N/A

## How to Manually Test
- Checkout to this branch
- Open README.MD file
- Hit (ctrl+shift+v) to README.MD file to preview badge

## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have linted my code prior to submission
- [x] I have made corresponding changes to the documentation
- [ ] My changes generates no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

## Design prototype link(s) (for UI stories)
[Locale Filtering] (https://xd.adobe.com/view/5d663f7d-a51d-421e-61e0-c4f3dca65798-2b57/)

## JIRA
[Filmo-001](https://airtable.com/tblPPdIAj35p2cawr/viwBzss5f7lYgfMV9/recEyOVQ0EFnIp0Fh)

### CODE REVIEW

**Comment by dnuwa** [comment]
@BenjaminKyamanywa always remember to add your teammates to as reviews otherwise, everything looks good to me.

**Comment by BenjaminKyamanywa** [comment]
> @BenjaminKyamanywa always remember to add your teammates to as reviews otherwise, everything looks good to me.

Thanks will remember to do so.

**Comment by dnuwa** [comment]
@BenjaminKyamanywa please rebase this PR ASAP so it can get merged.

**Comment by BenjaminKyamanywa** [comment]
> @BenjaminKyamanywa please rebase this PR ASAP so it can get merged.

Copy.

**Comment by BenjaminKyamanywa** [comment]
> Good job @BenjaminKyamanywa, However you should change the `How to test` section in your PR to exactly show us the way we can test your branch

Copy. Received. thanks for catching that.

**Comment by BenjaminKyamanywa** [comment]
> Good job @BenjaminKyamanywa, However you should change the `How to test` section in your PR to exactly show us the way we can test your branch

@WinnersProx changes on how to test have been made.

**Pull request merged**
